### ISSUE TITLE
script "edge_density" is missing in folder

### ISSUE THREAD

**Issue by NirDiamant** [omercelik-cs/Facial-Attractiveness-Analysis#1]
In generate_features.py there is a use of edge_density importing canny_edge_density,
though the file "edge_density.py" does not exist in the folder.
I find you work very usefull and would like to be able to use it ASAP.
thanks a lot!

**Comment by omercelik-cs** [comment]
Hi, edge density has no significance for the performance. I just forgot to remove it from the code. Thanks for your remark!
